### ISSUE TITLE
Extraneous files in your master branch

### ISSUE THREAD

**Issue by Baddaboo** [keristianfarra/visitSeattle#1]
You have `node_modules` and `.DS_Store` files in your master branch of your project. Use `git rm` to remove them (more info: https://stackoverflow.com/questions/7434449/why-use-git-rm-to-remove-a-file-instead-of-rm)

**Comment by keristianfarra** [comment]
do i say node_module git rm or git rm node_module  or just git rm

**Comment by Baddaboo** [comment]
> Answered on slack

**Comment by Baddaboo** [comment]
Closing because it looks like this was fixed in 009a25823dd6eaf48df5f45af1954b9601d8c832
