### ISSUE TITLE
Your AppBar will disappear when you click any of these tabs

### ISSUE THREAD

**Issue by Baddaboo** [keristianfarra/visitSeattle#3]
https://github.com/keristianfarra/visitSeattle/blob/aed7745da46d27062dd5ffc99f7a170945530846/src/components/Home.js#L48

Since your tabs are part of your `Home` component, they will disappear when the user clicks on a tab and `BrowserRouter` switches to a different page. I'm not sure if this is the behavior you want

**Comment by peachkat** [comment]
We (I) have absolutely no idea what we're doing.

**Comment by Baddaboo** [comment]
Closing because it looks like this issue was fixed in 009a258
